// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © mediplex

//@version=4
study("RSI")

i_source = input(defval = close, type = input.source, title = 'Source') // on downtrend use low / on uptrend use high
i_resolution  = input(defval = '', type = input.resolution, title = 'RSI Resolution')


i_rsi_length  = input(defval = 14, type = input.integer, title = 'RSI Length')
i_pivot_right_length  = input(defval = 1, type = input.integer, title = 'Pivot Right Length')
i_pivot_left_length  = input(defval = 1, type = input.integer, title = 'Pivot Left Length')

price  =  security(symbol = syminfo.tickerid, expression = i_source, resolution = i_resolution, lookahead=barmerge.lookahead_on)
rsi = rsi(price, i_rsi_length)

rsi_pl = pivotlow(rsi, i_pivot_left_length, i_pivot_right_length)
price_pl = pivotlow(price, i_pivot_left_length, i_pivot_right_length)

rsi_ph = pivothigh(rsi, i_pivot_left_length, i_pivot_right_length)
price_ph = pivothigh(price, i_pivot_left_length, i_pivot_right_length)


c_rsi_points = rsi >= 66.66 or rsi <= 33.33 ? color.purple : color.white 


plot(rsi, linewidth = 1, color = color.white, offset = -1)
plot(rsi, style = plot.style_circles, linewidth = 2, color = c_rsi_points, offset = -1)


// Bullish Divergences
f_isBullishDivergence(_p1, _p2, _o1, _o2) =>
    var string d = ''
    if _p1 > _p2 and _o1 < _o2 // S	LL	HL
        d := 'Strong Bullish Divergence'
    else if _p1 == _p2 and _o1 < _o2 // M   __	HL	
        d := 'Medium Bulish Divergence'
    else if _p1 > _p2 and _o1 == _o2 // W   LL	__
        d := 'Weak Bullish Divergence'
    else if _p1 < _p2 and _o1 > _o2 // H    HL	LL
        d := 'Hidden Bullish Divergence'


// Bearish Divergences
f_isBearishDivergence(_p1, _p2, _o1, _o2) =>
    var string d = ''
    if _p1 < _p2 and _o1 > _o2 // S    HH	LH
        d := 'Strong Bearish Divergence'
    else if _p1 == _p2 and _o1 < _o2 // M   __	HH	
        d := 'Medium Bearish Divergence'
    else if _p1 < _p2 and _o1 == _o2  // W  HH	__
        d := 'Weak Bearish Divergence'
    else if _p1 > _p2 and _o1 < _o2 // H  LH	HH
        d := 'Hidden Bearish Divergence'
    d

    







if not(na(rsi_pl)) and not(na(price_pl)) and time/1000/60/60/24 > timenow/1000/60/60/24 -30 // 30days // 
    array.push(bar_index_array,bar_index-1)
    array.push(rsi_array,rsi[1])
    array.push(price_array,low[1])
    //label.new(bar_index[1],rsi[1]-3, style=label.style_label_up, size=size.tiny, color=color.red)



if barstate.islast and array.size(bar_index_array) >= 2
    label.new(bar_index,rsi, style=label.style_label_left, size=size.normal,text=tostring(array.size(bar_index_array)), color=color.white)
    
    for i=0 to array.size(bar_index_array)-2
        //if i < array.size(bar_index_array)-1
        for j=i+1 to array.size(bar_index_array)-1
    
            hidden_bullish_divergence = array.get(rsi_array,i)>array.get(rsi_array,j) and array.get(price_array,i)<array.get(price_array,j)
            
            label.new(array.get(bar_index_array,i), array.get(rsi_array,i), style=label.style_label_up, size=size.normal, color=color.green, text='i', textcolor=color.white  )
            label.new(array.get(bar_index_array,j), array.get(rsi_array,j), style=label.style_label_up, size=size.normal, color=color.green, text='j', textcolor=color.white )
            if hidden_bullish_divergence //and array.get(bar_index_array,i)>array.get(bar_index_array,j)
                
                line.new(array.get(bar_index_array,i), array.get(rsi_array,i), array.get(bar_index_array,j), array.get(rsi_array,j), width=2, color=color.green)
           



